# Form implementation generated from reading ui file 'lesson6.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(500, 200, 270, 270))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/image/images/mindx_logo.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 800, 160))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/image/images/mindx_banner.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 190, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Nunito Sans")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #75061e;\n"
"font: 28pt \"Nunito Sans\";")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_emal = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_emal.setGeometry(QtCore.QRect(50, 270, 400, 50))
        self.lineEdit_emal.setStyleSheet("/* Chỉnh font chữ */\n"
"font: 12pt \"Nunito Sans\";\n"
"/* lùi lề trái*/\n"
"padding-left: 12px;\n"
"/* Độ cong của viền */\n"
"border-radius: 20px;\n"
"/* Chỉnh viền: độ dày - kiểu - màu */\n"
"border: 2px solid rgb(255, 25, 28);\n"
"")
        self.lineEdit_emal.setObjectName("lineEdit_emal")
        self.lineEdit_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(50, 350, 400, 50))
        self.lineEdit_password.setStyleSheet("/* Chỉnh font chữ */\n"
"font: 12pt \"Nunito Sans\";\n"
"/* lùi lề trái*/\n"
"padding-left: 12px;\n"
"/* Độ cong của viền */\n"
"border-radius: 20px;\n"
"/* Chỉnh viền: độ dày - kiểu - màu */\n"
"border: 2px solid rgb(255, 25, 28);\n"
"")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(50, 420, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Nunito Sans")
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 470, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Nunito Sans")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"/* Chỉnh font chữ */\n"
"font: 20pt \"Nunito Sans\";\n"
"/* Chỉnh màu chữ */\n"
"color: white;\n"
"/* Chỉnh màu nền */\n"
"background-color: rgb(255, 83, 86);\n"
"/* Độ cong của viền */\n"
"border-radius: 20px;\n"
"/* Chỉnh viền: độ dày - kiểu - màu */\n"
"border: 2px solid rgb(255, 25, 28);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"/* Chỉnh màu chữ */\n"
"color:  rgb(255, 83, 86);\n"
"/* Chỉnh màu nền */\n"
"background-color: white;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Login"))
        self.lineEdit_emal.setPlaceholderText(_translate("MainWindow", "Email"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.checkBox.setText(_translate("MainWindow", "Remember me?"))
        self.pushButton.setText(_translate("MainWindow", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
